"""Data models for the LLM Critic Enhancement system.

This module defines the core data structures used throughout the critic system
to track validation results, query decomposition, retrieved documents, reasoning
checks, and overall critic state.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional


@dataclass
class ValidationResult:
    """Result of answer validation check.
    
    Attributes:
        passed: Boolean indicating if answer passes quality checks
        triggered_rule: Name of the rule that triggered failure (e.g., "length_exceeded",
                       "hedging_detected", "multiple_entities", "unknown_answer").
                       None if validation passed.
    """
    passed: bool
    triggered_rule: Optional[str] = None


@dataclass
class DecompositionResult:
    """Result of query decomposition into sub-queries.
    
    Attributes:
        sub_queries: List of 1-3 sub-questions extracted from the original query
        reasoning_plan: Description of how sub-answers combine to produce final answer
    
    Constraints:
        - sub_queries must contain 1-3 elements
        - Each sub-query must be a non-empty string
        - reasoning_plan must be a non-empty string
    """
    sub_queries: List[str]
    reasoning_plan: str
    
    def __post_init__(self):
        """Validate constraints after initialization."""
        if not (1 <= len(self.sub_queries) <= 3):
            raise ValueError(
                f"sub_queries must contain 1-3 elements, got {len(self.sub_queries)}"
            )
        if not all(isinstance(sq, str) and sq.strip() for sq in self.sub_queries):
            raise ValueError("All sub-queries must be non-empty strings")
        if not isinstance(self.reasoning_plan, str) or not self.reasoning_plan.strip():
            raise ValueError("reasoning_plan must be a non-empty string")


@dataclass
class Document:
    """A retrieved document with metadata.
    
    Attributes:
        text: Document content
        source: Document identifier or URL
        score: Retrieval relevance score
    """
    text: str
    source: str
    score: float


@dataclass
class ReasoningCheckResult:
    """Result of reasoning validation check.
    
    Attributes:
        action: Next action to take - one of "PASS", "RETRY_RETRIEVAL", "REGENERATE"
        missing_facts: List of sub-queries with missing facts (empty if all facts present)
        reasoning_explanation: Explanation of reasoning validation result
    
    Action Values:
        - PASS: Both facts and reasoning validated successfully
        - RETRY_RETRIEVAL: Some intermediate facts not retrieved
        - REGENERATE: Facts retrieved but reasoning invalid
    """
    action: str
    missing_facts: List[str] = field(default_factory=list)
    reasoning_explanation: str = ""
    
    def __post_init__(self):
        """Validate action value."""
        valid_actions = {"PASS", "RETRY_RETRIEVAL", "REGENERATE"}
        if self.action not in valid_actions:
            raise ValueError(
                f"action must be one of {valid_actions}, got '{self.action}'"
            )


@dataclass
class CriticState:
    """Tracks state across critic loop iterations.
    
    This dataclass maintains the complete state of the critic system as it
    iterates through validation, decomposition, retrieval, and reasoning checks.
    Used for debugging and analysis.
    
    Attributes:
        question: Original question being answered
        current_answer: Most recent answer generated
        iteration_count: Number of critic loop iterations completed
        sub_queries: Sub-questions generated by decomposer (None if not yet decomposed)
        reasoning_plan: Reasoning plan from decomposer (None if not yet decomposed)
        sub_query_contexts: Retrieved documents per sub-query (None if not yet retrieved)
        validation_history: List of all validation results from each iteration
    """
    question: str
    current_answer: str
    iteration_count: int = 0
    sub_queries: Optional[List[str]] = None
    reasoning_plan: Optional[str] = None
    sub_query_contexts: Optional[Dict[str, List[Document]]] = None
    validation_history: List[ValidationResult] = field(default_factory=list)
