"""Reasoning validation component for the LLM Critic Enhancement system.

This module implements LLM-based reasoning validation that checks whether
intermediate facts are retrieved and the reasoning plan holds in the generated
answer. The checker uses a single LLM prompt to validate both aspects, with
retry logic for malformed responses and fallback handling for missing fields.
"""

import json
import logging
from typing import Dict, List

from src.critic.models import Document, ReasoningCheckResult
from src.rag.generator import call_llm


logger = logging.getLogger(__name__)


# Maximum number of retries for malformed JSON responses
MAX_RETRIES = 2


def check_reasoning(
    question: str,
    sub_queries: List[str],
    sub_query_contexts: Dict[str, List[Document]],
    reasoning_plan: str,
    answer: str,
    max_retries: int = MAX_RETRIES
) -> ReasoningCheckResult:
    """
    Validates that intermediate facts are retrieved and reasoning holds.
    
    Uses an LLM to validate two aspects:
    1. INTERMEDIATE FACTS: For each sub-query, was the necessary information
       retrieved in the documents?
    2. REASONING PLAN: Does the generated answer follow the reasoning plan and
       correctly combine the intermediate facts?
    
    The function makes a single LLM call per attempt, parses the JSON response,
    implements decision logic based on validation results, and handles errors
    with retry logic and fallbacks.
    
    Args:
        question: Original question being answered
        sub_queries: List of sub-questions generated by decomposer
        sub_query_contexts: Retrieved documents per sub-query
        reasoning_plan: Expected reasoning chain from decomposer
        answer: Generated answer to validate
        max_retries: Maximum number of retry attempts for malformed JSON (default: 2)
    
    Returns:
        ReasoningCheckResult with action and validation details
        
    Decision Logic:
        - If facts_retrieved == True AND reasoning_valid == True:
            Return action="PASS"
        - Else If facts_retrieved == False:
            Return action="RETRY_RETRIEVAL" with missing_facts list
        - Else If reasoning_valid == False:
            Return action="REGENERATE"
    
    Error Handling:
        - Malformed JSON: Retries with clarified prompt (max 2 retries)
        - Missing validation fields: Defaults to facts_retrieved=False,
          reasoning_valid=False
        - LLM timeout/error: Defaults to action="PASS" (accept current answer)
    
    Examples:
        >>> contexts = {
        ...     "Who directed Inception?": [Document("Christopher Nolan directed", "doc1", 0.9)]
        ... }
        >>> result = check_reasoning(
        ...     "Where was the director of Inception born?",
        ...     ["Who directed Inception?", "Where was Christopher Nolan born?"],
        ...     contexts,
        ...     "Find director, then find birthplace",
        ...     "Christopher Nolan was born in London"
        ... )
        >>> result.action in ["PASS", "RETRY_RETRIEVAL", "REGENERATE"]
        True
    """
    # Try to validate with retries for malformed JSON
    for attempt in range(max_retries + 1):
        try:
            # Call LLM with reasoning validation prompt
            response_text = _call_reasoning_validation_llm(
                question,
                sub_queries,
                sub_query_contexts,
                reasoning_plan,
                answer,
                attempt
            )
            
            # Parse JSON response
            parsed = json.loads(response_text)
            
            # Extract validation results with defaults for missing fields
            facts_retrieved = parsed.get("facts_retrieved", False)
            missing_facts = parsed.get("missing_facts", [])
            reasoning_valid = parsed.get("reasoning_valid", False)
            reasoning_explanation = parsed.get("reasoning_explanation", "")
            
            # Ensure missing_facts is a list
            if not isinstance(missing_facts, list):
                logger.warning(f"missing_facts is not a list: {missing_facts}, defaulting to empty list")
                missing_facts = []
            
            # Implement decision logic
            if facts_retrieved and reasoning_valid:
                return ReasoningCheckResult(
                    action="PASS",
                    missing_facts=[],
                    reasoning_explanation=reasoning_explanation
                )
            elif not facts_retrieved:
                return ReasoningCheckResult(
                    action="RETRY_RETRIEVAL",
                    missing_facts=missing_facts,
                    reasoning_explanation=reasoning_explanation
                )
            else:  # facts_retrieved but not reasoning_valid
                return ReasoningCheckResult(
                    action="REGENERATE",
                    missing_facts=[],
                    reasoning_explanation=reasoning_explanation
                )
            
        except json.JSONDecodeError as e:
            logger.warning(f"Malformed JSON on attempt {attempt + 1}/{max_retries + 1}: {e}")
            if attempt >= max_retries:
                logger.error("Max retries reached for JSON parsing. Using default fallback.")
                return _create_default_fallback()
            # Continue to next retry attempt
            
        except Exception as e:
            # Catch any other unexpected errors (LLM timeout, network issues, etc.)
            logger.error(f"Unexpected error during reasoning validation: {e}")
            # Default to PASS action (accept current answer)
            return _create_default_fallback()
    
    # Should not reach here, but fallback just in case
    return _create_default_fallback()


def _call_reasoning_validation_llm(
    question: str,
    sub_queries: List[str],
    sub_query_contexts: Dict[str, List[Document]],
    reasoning_plan: str,
    answer: str,
    retry_attempt: int = 0
) -> str:
    """
    Calls the LLM with the reasoning validation prompt.
    
    Args:
        question: Original question
        sub_queries: List of sub-questions
        sub_query_contexts: Retrieved documents per sub-query
        reasoning_plan: Expected reasoning chain
        answer: Generated answer to validate
        retry_attempt: Current retry attempt number (0 for first attempt)
    
    Returns:
        Raw LLM response text (should be JSON)
    """
    system_prompt = _create_system_prompt(retry_attempt)
    user_prompt = _create_user_prompt(
        question,
        sub_queries,
        sub_query_contexts,
        reasoning_plan,
        answer
    )
    
    # Use temperature=0.2 for more deterministic validation
    return call_llm(system_prompt, user_prompt, temperature=0.2)


def _create_system_prompt(retry_attempt: int = 0) -> str:
    """
    Creates the system prompt for reasoning validation.
    
    Args:
        retry_attempt: Current retry attempt number (0 for first attempt)
    
    Returns:
        System prompt string
    """
    base_prompt = """You are validating whether a generated answer properly uses retrieved information and follows a reasoning plan.

Validate two things:
1. INTERMEDIATE FACTS: For each sub-query, was the necessary information retrieved in the documents?
2. REASONING PLAN: Does the generated answer follow the reasoning plan and correctly combine the intermediate facts?

Be thorough but fair in your validation. If the documents contain the necessary information and the answer follows the reasoning plan reasonably well, mark as valid."""
    
    if retry_attempt > 0:
        # Add clarification for retry attempts
        base_prompt += """

IMPORTANT: Your previous response had formatting issues. Please ensure you output ONLY valid JSON with no additional text."""
    
    return base_prompt


def _create_user_prompt(
    question: str,
    sub_queries: List[str],
    sub_query_contexts: Dict[str, List[Document]],
    reasoning_plan: str,
    answer: str
) -> str:
    """
    Creates the user prompt for reasoning validation.
    
    Args:
        question: Original question
        sub_queries: List of sub-questions
        sub_query_contexts: Retrieved documents per sub-query
        reasoning_plan: Expected reasoning chain
        answer: Generated answer to validate
    
    Returns:
        User prompt string with all validation context
    """
    # Format sub-queries and retrieved context
    context_parts = []
    for sub_query in sub_queries:
        documents = sub_query_contexts.get(sub_query, [])
        context_parts.append(f"\nSub-query: {sub_query}")
        
        if not documents:
            context_parts.append("  Retrieved documents: None")
        else:
            context_parts.append("  Retrieved documents:")
            for i, doc in enumerate(documents, 1):
                # Truncate long documents for prompt efficiency
                doc_text = doc.text[:500] + "..." if len(doc.text) > 500 else doc.text
                context_parts.append(f"    {i}. {doc_text}")
    
    context_str = "\n".join(context_parts)
    
    return f"""Original Question: {question}

Sub-queries and Retrieved Context:
{context_str}

Reasoning Plan: {reasoning_plan}

Generated Answer: {answer}

Output format (JSON):
{{
  "facts_retrieved": true/false,
  "missing_facts": ["sub-query 1", ...] or [],
  "reasoning_valid": true/false,
  "reasoning_explanation": "brief explanation of reasoning validation"
}}

Respond with ONLY the JSON object, no additional text."""


def _create_default_fallback() -> ReasoningCheckResult:
    """
    Creates a default fallback result when LLM fails or returns invalid results.
    
    Defaults to PASS action to accept the current answer and avoid infinite loops.
    
    Returns:
        ReasoningCheckResult with PASS action
    """
    logger.info("Using default fallback: accepting current answer (PASS)")
    return ReasoningCheckResult(
        action="PASS",
        missing_facts=[],
        reasoning_explanation="Validation failed, accepting answer by default"
    )
